dotnet pack ..\src\Abplus\Abplus.csproj -o ..\..\nupkg\
dotnet pack ..\src\Abplus.MqMessages\Abplus.MqMessages.csproj -o ..\..\nupkg\
dotnet pack ..\src\Abplus.MqMessages.AuditingStore\Abplus.MqMessages.AuditingStore.csproj -o ..\..\nupkg\
dotnet pack ..\src\Abplus.MqMessages.IndexToES\Abplus.MqMessages.IndexToES.csproj -o ..\..\nupkg\
dotnet pack ..\src\Abplus.MqMessages.RebusCore\Abplus.MqMessages.RebusCore.csproj -o ..\..\nupkg\
dotnet pack ..\src\Abplus.MqMessages.RebusRabbitMqConsumer\Abplus.MqMessages.RebusRabbitMqConsumer.csproj -o ..\..\nupkg\
dotnet pack ..\src\Abplus.MqMessages.RebusRabbitMqPublisher\Abplus.MqMessages.RebusRabbitMqPublisher.csproj -o ..\..\nupkg\
dotnet pack ..\src\Abplus.MqMessages.RedisStoreMessageTracker\Abplus.MqMessages.RedisStoreMessageTracker.csproj -o ..\..\nupkg\
dotnet pack ..\src\Abplus.T4.PermissionsFromJson\Abplus.T4.PermissionsFromJson.csproj -o ..\..\nupkg\
